
services:
  e-masjid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the_vault
    command: uv run gunicorn -b 0.0.0.0 -p 6989 core.wsgi:application
    volumes:
      - .:/app
    ports:
      - "6989:6989"
    env_file:
      - .env # Opsional: Gunakan file .env untuk variabel lingkungan